# Generated by Django 3.0.8 on 2020-07-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Mobile_No', models.IntegerField()),
            ],
        ),
    ]
